spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none #create-drop, update, validate, none
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
server:
  port: 8080

