### POST 쿠폰 생성
POST http://localhost:8080/business/coupons
Content-Type: application/json

{
  "performanceId": 1,
  "type": "PERCENT",
  "value": 10,
  "expiredAt": "2022-06-30 00:00:00",
  "amount": 10
}
